name: "Barechek Newrelic Metric Reporter"
author: "Barecheck"
description: "Sends Barecheck metrics to the newrelic as custom events"
branding:
  icon: "upload-cloud"
  color: "yellow"
inputs:
  insertApiKey:
    description: "Your New Relic Insert API key."
    required: true
  accountId:
    description: "Your New Relic account ID. Custom events representing your test run will be posted to this account."
    required: true
  metricName:
    description: "Your Barecheck metric that you would like to receive as an event"
    required: true
  metricValue:
    description: "Barecheck metric value."
    required: true
  application:
    description: "Application from where metrics come"
    required: false
    default: ""
  region:
    description: "The geographical region for your New Relic account - US or EU. Default: US"
    required: false
    default: US

runs:
  using: "docker"
  image: "Dockerfile"
  env:
    NEW_RELIC_INSERT_API_KEY: ${{ inputs.insertApiKey }}
    NEW_RELIC_ACCOUNT_ID: ${{ inputs.accountId }}
    EVENT_METRIC_NAME: ${{ inputs.metricName }}
    EVENT_METRIC_VALUE: ${{ inputs.metricValue }}
    EVENT_APPLICATION: ${{ inputs.application }}
    NEW_RELIC_REGION: ${{ inputs.region }}
